# Generated by Django 5.2.15 on 2026-06-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='is_paid',
            field=models.BooleanField(default=False, help_text='Designates whether the course fee has been paid.'),
        ),
    ]
