import os
import django
from django.core.management import call_command
from django.db import connection

# 1. Initialize Django
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings') # Ensure 'core' matches your settings folder name
django.setup()

# 2. Get the raw SQL commands generated by Django for your apps
print("Generating sequence reset SQL...")
apps_to_reset = ['instructors', 'students', 'courses', 'auth']
statements = call_command('sqlsequencereset', *apps_to_reset, stdout=None)

# 3. Execute the SQL directly against Neon via Django's connection
if statements:
    print("Executing sequence optimization on Neon Postgres...")
    with connection.cursor() as cursor:
        for sql in statements.split('\n'):
            clean_sql = sql.strip()
            if clean_sql and not clean_sql.startswith('--'):
                cursor.execute(clean_sql)
    print("🎉 SUCCESS: All database primary key sequences have been updated!")
else:
    print("No sequences needed resetting or apps could not be read.")
