# Generated by Django 5.2.14 on 2026-07-12 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='adminpanel__created_f00b4a_idx',
            old_name='adminpanel__created_c4b2a1_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='adminpanel__content_83a139_idx',
            old_name='adminpanel__content_9e3f6b_idx',
        ),
    ]
