# Generated by Django 5.2.14 on 2026-06-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_free',
            field=models.BooleanField(default=False, help_text='If checked, all logged-in users can access lessons without enrollment or payment.'),
        ),
    ]
