# Generated by Django 5.2.14 on 2026-06-15 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_tag_course_updated_at_course_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, help_text='Unique identifier used in URLs and system queries. Automatically generated if empty.', max_length=100, null=True, unique=True),
        ),
    ]
