# Generated by Django 5.2.14 on 2026-06-10 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instructors', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='experience_years',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='instructor',
            name='specialty',
            field=models.CharField(default='Expert Mentor', max_length=100),
        ),
    ]
