# Generated by Django 5.2.14 on 2026-06-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0003_alter_assignment_options_alter_assignment_max_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(blank=True, help_text='Upload instruction document, template files, or project resources (PDF, ZIP, DOCX).', null=True, upload_to='assignments/files/'),
        ),
    ]
