# Generated by Django 5.2.14 on 2026-06-14 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0004_assignment_assignment_file'),
        ('courses', '0004_course_is_free'),
        ('lessons', '0002_alter_lesson_options_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assignment',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='lessons.lesson'),
        ),
    ]
