# Generated by Django 5.2.14 on 2026-07-12 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_studentanswer_points_earned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='sample_answer',
            field=models.TextField(blank=True, help_text='Optional model answer shown to instructors while grading short answers.'),
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='needs_grading',
            field=models.BooleanField(default=False, help_text='True while this attempt has ungraded short-answer questions.'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_answers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='is_graded',
            field=models.BooleanField(default=True, help_text='False only for short-answer questions awaiting manual grading; auto-graded types are always True.'),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='text_answer',
            field=models.TextField(blank=True, help_text='Free-text response for short-answer questions.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE', 'Single Choice'), ('MULTIPLE', 'Multiple Choice'), ('TRUE_FALSE', 'True / False'), ('SHORT_ANSWER', 'Short Answer')], default='SINGLE', max_length=15),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage score. Provisional (auto-graded questions only) until any short-answer questions are graded.', max_digits=5, null=True),
        ),
    ]
